
FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /Counter_UAS

# Install System Packages

RUN apt-get update && \
    apt-get install -y build-essential && \
    rm -rf /var/lib/apt/lists/*

# Python Dependencies

COPY requirements/backend.txt requirements/

RUN pip install \
    --upgrade pip && \
    pip install \
    --default-timeout=300 \
    --no-cache-dir \
    -r requirements/backend.txt

# Copy Backend Source

COPY backend/ backend/

# Expose FastAPI Port

EXPOSE 8000

# Start Backend

CMD ["python3", "-m", "backend.main"]